apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"-1"},"finalizers":["resources-finalizer.argocd.argoproj.io"],"name":"dev-additional-providers","namespace":"argocd"},"spec":{"destination":{"namespace":"crossplane-system","server":"https://kubernetes.default.svc"},"project":"default","source":{"directory":{"recurse":true},"path":"platform/providers","repoURL":"git@github.com:ims-platform-dev/portal-kombat.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"retry":{"backoff":{"duration":"10s","factor":2,"maxDuration":"3m"},"limit":3},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2025-11-04T22:01:32Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 157
  name: dev-additional-providers
  namespace: argocd
  resourceVersion: "2843683"
  uid: 67bd3f09-0f1d-41ac-a407-1c1e9289cbb4
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: platform/providers
    repoURL: git@github.com:ims-platform-dev/portal-kombat.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
      limit: 3
    syncOptions:
    - CreateNamespace=true
status:
  conditions:
  - lastTransitionTime: "2025-11-05T00:16:55Z"
    message: 'Failed to load live state: failed to get cluster info for "https://kubernetes.default.svc":
      error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: ComparisonError
  - lastTransitionTime: "2025-11-05T00:56:38Z"
    message: 'Failed to load target state: failed to get cluster version for cluster
      "https://kubernetes.default.svc": failed to get cluster info for "https://kubernetes.default.svc":
      error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: ComparisonError
  - lastTransitionTime: "2025-11-05T00:56:38Z"
    message: 'error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: UnknownError
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-11-04T22:47:10Z"
    status: Healthy
  history:
  - deployStartedAt: "2025-11-04T22:01:32Z"
    deployedAt: "2025-11-04T22:01:33Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: platform/providers
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:01:55Z"
    deployedAt: "2025-11-04T22:02:00Z"
    id: 1
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: platform/providers
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:05:22Z"
    deployedAt: "2025-11-04T22:05:23Z"
    id: 2
    initiatedBy:
      username: admin
    revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: platform/providers
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:37:24Z"
    deployedAt: "2025-11-04T22:37:26Z"
    id: 3
    initiatedBy:
      username: admin
    revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: platform/providers
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:40:05Z"
    deployedAt: "2025-11-04T22:40:07Z"
    id: 4
    initiatedBy:
      username: admin
    revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: platform/providers
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  operationState:
    finishedAt: "2025-11-04T22:40:07Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry:
        backoff:
          duration: 10s
          factor: 2
          maxDuration: 3m
        limit: 3
      sync:
        revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2025-11-04T22:40:05Z"
    syncResult:
      resources:
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-apigateway unchanged
        name: provider-upjet-aws-apigateway
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-sqs unchanged
        name: provider-upjet-aws-sqs
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-eks unchanged
        name: provider-upjet-aws-eks
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-rds unchanged
        name: provider-upjet-aws-rds
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-iam unchanged
        name: provider-upjet-aws-iam
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-ec2 unchanged
        name: provider-upjet-aws-ec2
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-lambda unchanged
        name: provider-upjet-aws-lambda
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-kms unchanged
        name: provider-upjet-aws-kms
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-sns unchanged
        name: provider-upjet-aws-sns
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-cloudwatchlogs unchanged
        name: provider-upjet-aws-cloudwatchlogs
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-cloudwatch unchanged
        name: provider-upjet-aws-cloudwatch
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-s3 unchanged
        name: provider-upjet-aws-s3
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-vpc unchanged
        name: provider-upjet-aws-vpc
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-dynamodb unchanged
        name: provider-upjet-aws-dynamodb
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: pkg.crossplane.io
        hookPhase: Running
        kind: Provider
        message: provider.pkg.crossplane.io/provider-upjet-aws-elasticache unchanged
        name: provider-upjet-aws-elasticache
        namespace: crossplane-system
        status: Synced
        syncPhase: Sync
        version: v1
      revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: platform/providers
        repoURL: git@github.com:ims-platform-dev/portal-kombat.git
        targetRevision: main
  reconciledAt: "2025-11-05T00:56:38Z"
  resourceHealthSource: appTree
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: crossplane-system
        server: https://kubernetes.default.svc
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: platform/providers
        repoURL: git@github.com:ims-platform-dev/portal-kombat.git
        targetRevision: main
    status: Unknown
