apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2025-11-02T12:28:30Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 916
  name: dev-root
  namespace: argocd
  resourceVersion: "2857242"
  uid: 904ccefd-d9ec-4b93-aa68-808a2d30cd9d
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{platform-apps.yaml,infrastructure-apps.yaml}'
      jsonnet: {}
    path: environments/dev/argocd
    repoURL: git@github.com:ims-platform-dev/portal-kombat.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  conditions:
  - lastTransitionTime: "2025-11-04T23:29:59Z"
    message: 'Failed to load live state: failed to get cluster info for "https://kubernetes.default.svc":
      error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: ComparisonError
  - lastTransitionTime: "2025-11-05T00:59:30Z"
    message: 'Failed to load target state: failed to get cluster version for cluster
      "https://kubernetes.default.svc": failed to get cluster info for "https://kubernetes.default.svc":
      error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: ComparisonError
  - lastTransitionTime: "2025-11-05T00:59:30Z"
    message: 'error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: UnknownError
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-11-02T13:37:37Z"
    status: Healthy
  history:
  - deployStartedAt: "2025-11-03T11:17:27Z"
    deployedAt: "2025-11-03T11:17:28Z"
    id: 15
    initiatedBy:
      automated: true
    revision: 93f92e4bed4185f45d6066dee32edebcb8064e46
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-03T11:21:39Z"
    deployedAt: "2025-11-03T11:21:39Z"
    id: 16
    initiatedBy:
      automated: true
    revision: 06e43eaec93366902622e874a69df9edb7e1e828
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-03T11:24:21Z"
    deployedAt: "2025-11-03T11:24:22Z"
    id: 17
    initiatedBy:
      automated: true
    revision: b7479eb53b7636122ad19c561e9e74d6b3193f8c
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:31:09Z"
    deployedAt: "2025-11-04T21:31:10Z"
    id: 18
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:33:18Z"
    deployedAt: "2025-11-04T21:33:19Z"
    id: 19
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:33:49Z"
    deployedAt: "2025-11-04T21:33:50Z"
    id: 20
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:49:57Z"
    deployedAt: "2025-11-04T21:49:58Z"
    id: 21
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:56:04Z"
    deployedAt: "2025-11-04T21:56:06Z"
    id: 22
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:37:26Z"
    deployedAt: "2025-11-04T22:37:28Z"
    id: 23
    initiatedBy:
      username: admin
    revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:40:07Z"
    deployedAt: "2025-11-04T22:40:09Z"
    id: 24
    initiatedBy:
      username: admin
    revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
    source:
      directory:
        include: '{platform-apps.yaml,infrastructure-apps.yaml}'
        jsonnet: {}
      path: environments/dev/argocd
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  operationState:
    finishedAt: "2025-11-04T22:40:09Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2025-11-04T22:40:07Z"
    syncResult:
      resources:
      - group: argoproj.io
        hookPhase: Running
        kind: Application
        message: application.argoproj.io/dev-platform-crossplane unchanged
        name: dev-platform-crossplane
        namespace: argocd
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      - group: argoproj.io
        hookPhase: Running
        kind: Application
        message: application.argoproj.io/dev-provider-configs unchanged
        name: dev-provider-configs
        namespace: argocd
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      - group: argoproj.io
        hookPhase: Running
        kind: Application
        message: application.argoproj.io/dev-infrastructure unchanged
        name: dev-infrastructure
        namespace: argocd
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
      source:
        directory:
          include: '{platform-apps.yaml,infrastructure-apps.yaml}'
          jsonnet: {}
        path: environments/dev/argocd
        repoURL: git@github.com:ims-platform-dev/portal-kombat.git
        targetRevision: main
  reconciledAt: "2025-11-05T00:59:30Z"
  resourceHealthSource: appTree
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        directory:
          include: '{platform-apps.yaml,infrastructure-apps.yaml}'
          jsonnet: {}
        path: environments/dev/argocd
        repoURL: git@github.com:ims-platform-dev/portal-kombat.git
        targetRevision: main
    status: Unknown
