apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: dev-root:argoproj.io/Application:argocd/dev-infrastructure
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"dev-root:argoproj.io/Application:argocd/dev-infrastructure"},"finalizers":["resources-finalizer.argocd.argoproj.io"],"name":"dev-infrastructure","namespace":"argocd"},"spec":{"destination":{"namespace":"default","server":"https://kubernetes.default.svc"},"ignoreDifferences":[{"group":"aws.plt.intelerad.io","jqPathExpressions":[".spec.parameters.providerConfig",".spec.compositionRef",".spec.compositionRevisionRef",".spec.resourceRef",".spec.compositeDeletePolicy"],"kind":"ObjectStorage","managedFieldsManagers":["crossplane"]},{"group":"aws.plt.intelerad.io","jqPathExpressions":[".spec.parameters.providerConfig",".spec.compositionRef",".spec.compositionRevisionRef",".spec.resourceRef",".spec.compositeDeletePolicy"],"kind":"EC2Instance","managedFieldsManagers":["crossplane"]}],"project":"default","source":{"directory":{"recurse":true},"path":"environments/dev/infrastructure","repoURL":"git@github.com:ims-platform-dev/portal-kombat.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"retry":{"backoff":{"duration":"10s","factor":2,"maxDuration":"5m"},"limit":5},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2025-11-02T12:28:30Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 5016
  name: dev-infrastructure
  namespace: argocd
  resourceVersion: "2844209"
  uid: 46a48f26-3569-4930-8f25-78c9572411df
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: aws.plt.intelerad.io
    jqPathExpressions:
    - .spec.parameters.providerConfig
    - .spec.compositionRef
    - .spec.compositionRevisionRef
    - .spec.resourceRef
    - .spec.compositeDeletePolicy
    kind: ObjectStorage
    managedFieldsManagers:
    - crossplane
  - group: aws.plt.intelerad.io
    jqPathExpressions:
    - .spec.parameters.providerConfig
    - .spec.compositionRef
    - .spec.compositionRevisionRef
    - .spec.resourceRef
    - .spec.compositeDeletePolicy
    kind: EC2Instance
    managedFieldsManagers:
    - crossplane
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: environments/dev/infrastructure
    repoURL: git@github.com:ims-platform-dev/portal-kombat.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
      limit: 5
    syncOptions:
    - CreateNamespace=true
status:
  conditions:
  - lastTransitionTime: "2025-11-05T00:13:07Z"
    message: 'Failed to load live state: failed to get cluster info for "https://kubernetes.default.svc":
      error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: ComparisonError
  - lastTransitionTime: "2025-11-05T00:56:45Z"
    message: 'Failed to load target state: failed to get cluster version for cluster
      "https://kubernetes.default.svc": failed to get cluster info for "https://kubernetes.default.svc":
      error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: ComparisonError
  - lastTransitionTime: "2025-11-05T00:56:45Z"
    message: 'error synchronizing cache state : failed to sync cluster https://172.20.0.1:443:
      failed to load initial state of resource BucketLifecycleConfiguration.s3.aws.upbound.io:
      failed to list resources: conversion webhook for s3.aws.upbound.io/v1beta1,
      Kind=BucketLifecycleConfiguration failed: json: cannot unmarshal string into
      Go struct field RuleFilterObservation.status.atProvider.rule.filter.objectSizeGreaterThan
      of type float64'
    type: UnknownError
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-11-03T07:57:02Z"
    status: Healthy
  history:
  - deployStartedAt: "2025-11-04T06:35:52Z"
    deployedAt: "2025-11-04T06:35:53Z"
    id: 66
    initiatedBy:
      automated: true
    revision: 64e6b199166dfa38acb3fe92ea3b647e84a9e896
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T06:57:54Z"
    deployedAt: "2025-11-04T06:57:54Z"
    id: 67
    initiatedBy:
      username: admin
    revision: 64e6b199166dfa38acb3fe92ea3b647e84a9e896
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:31:04Z"
    deployedAt: "2025-11-04T21:31:05Z"
    id: 68
    initiatedBy:
      automated: true
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:33:48Z"
    deployedAt: "2025-11-04T21:33:49Z"
    id: 69
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:54:58Z"
    deployedAt: "2025-11-04T21:54:59Z"
    id: 70
    initiatedBy:
      automated: true
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:56:03Z"
    deployedAt: "2025-11-04T21:56:04Z"
    id: 71
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T21:56:25Z"
    deployedAt: "2025-11-04T21:56:26Z"
    id: 72
    initiatedBy:
      username: admin
    revision: 192254e4043c9e1fd54cddd6e828bb44fa153524
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:05:29Z"
    deployedAt: "2025-11-04T22:05:30Z"
    id: 73
    initiatedBy:
      automated: true
    revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:37:25Z"
    deployedAt: "2025-11-04T22:37:27Z"
    id: 74
    initiatedBy:
      username: admin
    revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  - deployStartedAt: "2025-11-04T22:40:06Z"
    deployedAt: "2025-11-04T22:40:08Z"
    id: 75
    initiatedBy:
      username: admin
    revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: environments/dev/infrastructure
      repoURL: git@github.com:ims-platform-dev/portal-kombat.git
      targetRevision: main
  operationState:
    finishedAt: "2025-11-04T22:44:17Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        backoff:
          duration: 10s
          factor: 2
          maxDuration: 5m
        limit: 5
      sync:
        autoHealAttemptsCount: 6
        prune: true
        resources:
        - group: aws.plt.intelerad.io
          kind: ObjectStorage
          name: portal-kombat-app-data-bucket
        - group: aws.plt.intelerad.io
          kind: XObjectStorage
          name: my-app-uploads-bucket-lnnfx
        - group: aws.plt.intelerad.io
          kind: XEC2Instance
          name: portal-kombat-dev-app-server-6hp2s
        - group: aws.plt.intelerad.io
          kind: XObjectStorage
          name: portal-kombat-app-data-bucket-j4xq6
        revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2025-11-04T22:44:16Z"
    syncResult:
      resources:
      - group: aws.plt.intelerad.io
        hookPhase: Running
        kind: ObjectStorage
        message: objectstorage.aws.plt.intelerad.io/portal-kombat-app-data-bucket
          configured
        name: portal-kombat-app-data-bucket
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      revision: ad9f1dce160e013b7926e0f078c96fc9cfd1d43b
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: environments/dev/infrastructure
        repoURL: git@github.com:ims-platform-dev/portal-kombat.git
        targetRevision: main
  reconciledAt: "2025-11-05T00:56:24Z"
  resourceHealthSource: appTree
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: aws.plt.intelerad.io
        jqPathExpressions:
        - .spec.parameters.providerConfig
        - .spec.compositionRef
        - .spec.compositionRevisionRef
        - .spec.resourceRef
        - .spec.compositeDeletePolicy
        kind: ObjectStorage
        managedFieldsManagers:
        - crossplane
      - group: aws.plt.intelerad.io
        jqPathExpressions:
        - .spec.parameters.providerConfig
        - .spec.compositionRef
        - .spec.compositionRevisionRef
        - .spec.resourceRef
        - .spec.compositeDeletePolicy
        kind: EC2Instance
        managedFieldsManagers:
        - crossplane
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: environments/dev/infrastructure
        repoURL: git@github.com:ims-platform-dev/portal-kombat.git
        targetRevision: main
    status: Unknown
