---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: austin.carter@intelerad.com
    privateKeySecretRef:
      name: letsencrypt-prod-dns
    solvers:
    - dns01:
        route53:
          region: us-east-2
   
          hostedZoneID: Z05914812OPX7495S4MSP
         
      selector:
        dnsZones:
        - 'plt-dev.inteleradhealth.com'
        - '*.plt-dev.inteleradhealth.com'
