---
# Management account provider config
# Uses IRSA to assume role in management account
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: management-account
spec:
  credentials:
    source: IRSA
  assumeRoleChain:
    - roleARN: arn:aws:iam::873031875931:role/cross_account_management