---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: platform-prod
spec:
  credentials:
    source: IRSA
  assumeRoleChain:
    - roleARN: arn:aws:iam::873031875931:role/cross_account_management
    - roleARN: arn:aws:iam::637423399955:role/cross_account_admin