---
# Application Workloads
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-s3reader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ims-platform-dev/portal-kombat.git
    targetRevision: main
    path: environments/dev/workloads/s3reader
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
