# apiVersion: aws.plt.intelerad.io/v1alpha1
# kind: VPCNetwork
# metadata:
#   name: platform-prod-shared-vpc
#   namespace: default
# spec:
#   parameters:
#     vpcCidr: 10.100.0.0/16
#     region: us-east-2
#     availabilityZones:
#       - us-east-2a
#       - us-east-2b
#       - us-east-2c


#     publicSubnets:
#       - name: prod-shared-public-a
#         cidr: 10.100.0.0/20    
#         az: us-east-2a
#         mapPublicIpOnLaunch: true
#       - name: prod-shared-public-b
#         cidr: 10.100.16.0/20     
#         az: us-east-2b
#         mapPublicIpOnLaunch: true
#       - name: prod-shared-public-c
#         cidr: 10.100.32.0/20    
#         az: us-east-2c
#         mapPublicIpOnLaunch: true


#     privateSubnets:
#       - name: prod-shared-private-a
#         cidr: 10.100.48.0/20   
#         az: us-east-2a
#       - name: prod-shared-private-b
#         cidr: 10.100.64.0/20     
#         az: us-east-2b
#       - name: prod-shared-private-c
#         cidr: 10.100.80.0/20   
#         az: us-east-2c


#     natGateway:
#       enabled: true
#       publicSubnetName: prod-shared-public-a
#       allocateElasticIp: true


#     tags:
#       managedBy: Crossplane
#       project: portal-kombat
#       environment: production
#       additional:
#         CostCenter: platform-networking
#         Compliance: "true"
#     providerConfig: platform-prod-account
#   writeConnectionSecretToRef:
#     name: platform-prod-vpc-connection