---
# Default EC2NodeClass for general workloads
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: raiden-control-plane

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: raiden-control-plane

  role: karpenter_node_role

  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh raiden-control-plane

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        iops: 3000
        throughput: 125
        encrypted: true
        deleteOnTermination: true

  tags:
    Environment: dev
    ManagedBy: Karpenter
    Project: portal-kombat
    Cluster: raiden-control-plane

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
