# Cluster configuration (required)
clusterName: raiden-control-plane
clusterEndpoint: https://31F74548D0C0D4910526F1FBE62C72B5.gr7.us-east-2.eks.amazonaws.com

# Service Account with IRSA
serviceAccount:
    create: true
    name: karpenter
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::654654563406:role/karpenter_controller_role-raiden-control-plane

# High availability
replicas: 2

# Controller configuration
controller:
  env:
  - name: CLUSTER_NAME
    value: raiden-control-plane
  - name: CLUSTER_ENDPOINT
    value: https://31F74548D0C0D4910526F1FBE62C72B5.gr7.us-east-2.eks.amazonaws.com
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

# Affinity for controller pods
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/controller
          operator: DoesNotExist
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: karpenter
        topologyKey: kubernetes.io/hostname

# Prevent karpenter from scaling down nodes with karpenter pods
tolerations:
- key: CriticalAddonsOnly
  operator: Exists

# Webhook
webhook:
  enabled: true
  port: 8443
